### ISSUE TITLE
Certificate Config: Print preview with handles not dummy data

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3024]
**Describe the bug**
- Print. Should print the preview image. Not the version with handlebars

IMPROVEMENT:
!! use upload flow/pattern used elsewhere (eg. gov logo upload).  sorry JPF mistake.... https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=2289%3A33690

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Certificate Config
2. Click on Print 
3. Notice the print preview doesn't show version with dummy data

**Expected behaviour**
Print preview should be the same as Preview with dummy data

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/b21f9ca9-7eb7-4732-83aa-a50a488b2716)

**Comment by euanmillar** [comment]
Should be fixed already

**Comment by SyedaAfrida** [comment]
@anny320 This bug is not fixed
**preview of birth**
![preview of birth](https://user-images.githubusercontent.com/94350336/171805040-4c0649d5-21af-4b90-b175-8e9a0bfcb135.png)
**When printed birth**
![print of birth](https://user-images.githubusercontent.com/94350336/171805180-5feab3be-735b-4c3a-83ba-78fca668ec0a.png)
**Preview of death**
![preview of death](https://user-images.githubusercontent.com/94350336/171805195-89e846cd-9592-4a5a-81a7-0812af6dd8c4.png)
**when printed death**
![print of death](https://user-images.githubusercontent.com/94350336/171805284-20c8cdc3-51bc-4836-8ffb-a45a3032a5c4.png)

**Comment by jpye-finch** [comment]
have you tried changing the print settings to A5?

**Comment by SyedaAfrida** [comment]
@anny320 this bug has passed and can be closed
![print of birth](https://user-images.githubusercontent.com/94350336/172359118-62d3ff97-7613-4abd-b709-c9e4c99f9281.png)
![print of death](https://user-images.githubusercontent.com/94350336/172359129-9290d81e-4170-4121-ab0e-c1bff7f6c944.png)

**Comment by anny320** [comment]
completed
