### ISSUE TITLE
In performance, Informant column is showing blank in Registration by status

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6157]
**Bug description:**
In performance, Informant column is showing blank in Registration by status

**Steps to reproduce:**
1. Login to RA/ local Registrar
2. Click Performance
3. Filter any office
4. In Regsitration by status click any link
5. Observe informant column

**Actual result:**
In performance, Informant column is showing blank in Registration by status

**Expected result:**
Should show relationship to child / deceased and email address

**Screenshot:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/8cd29cf9-3141-43fc-a14f-e7d96a39c988

**Tested on:**
https://login.niue.opencrvs.org/?lang=en

**Comment by SyedaAfrida** [comment]
This bug is also in core

**Comment by Nil20** [comment]
Fix: https://github.com/opencrvs/opencrvs-core/issues/6157

**Comment by Zangetsu101** [comment]
This needs to be cherry-picked for Niue

**Comment by Zangetsu101** [comment]
Older declarations _might_ not show the proper value on 1.5, it should get fixed automatically in 1.6

**Comment by SyedaAfrida** [comment]
Will be tested in V1.6.0

**Comment by tiri39** [comment]
Found following issues - 

1. For **some of the old declarations** (created in v1.5.0) the **relationship to child / deceased is not showing** in the informant column.

https://github.com/user-attachments/assets/f94151f4-9d3a-4d69-b29d-f5bceb0cd4d1


2. When the informant is **Someone Else** , for the old declarations the Informant column shows the specific relationship (for ex - uncle / aunt etc.) that was provided while creating the declaration; but for new (created in v1.6.0) declarations it shows **Other family member** . Should show **Someone else** or the specific relationship.

https://github.com/user-attachments/assets/a4616af8-f67b-4ac8-9a0d-59b3da48860d

**Comment by euanmillar** [comment]
@jpye-finch I am moving this to 1.7.0 as the Performance re-design #6261  may mean that a bugfix in this area is not required.

**Comment by Siyasanga** [comment]
Hi @tiri39 I'm currently on the develop branch, and this issue seems to be fixed. Can you please confirm if you still experiencing this bug on your environment?

**Comment by Zangetsu101** [comment]
I think we can send it to the QA column now as the reindexing issue has been fixed, so this one should automatically get fixed as well

**Comment by onnee04** [comment]
@Siyasanga when we select "Someone else" as informant, it shows "other family member". 
Expected result: when we select "Someone else" as informant, it should show "Someone else". 

https://github.com/user-attachments/assets/8f635527-1f71-4814-a9d9-07d11b65d313

**Comment by tiri39** [comment]
Not Fixed.

Still shows 'Other family member' when 'someone else' is selected as informant.

https://github.com/user-attachments/assets/7d7e6293-2c93-482c-8d33-381b4e89436b
