### ISSUE TITLE
Record assignment discrepancy between Workqueue and Record Audit page when registrar unassigns another user from a record.

### ISSUE THREAD

**Issue by tiri39** [opencrvs/opencrvs-core#8516]
**Bug description:**

When registrar unassigns another user from a record and assigns himself, that user
- sees the record is assigned to the registrar in workqueue.
- sees the record is still assigned to himself in record audit page. 

**Steps to reproduce:**

1. Login as local registrar.
2. Navigate to any workqueue.
3. Unassign any user from a record and assign himself.
4. Logout and log in as the user who was unassigned previously.
5. Navigate to that workqueue and observe to whom that record is assigned to.
6. Click on the record to navigate to the record audit page.
7. Observe to whom that record is assigned to in the record audit page.

**Actual result:**
Record is displayed to be assigned to 
- the registrar who unassigned and assigned himself. (in workqueue)
- the user who was unassigned by the registrar. (in record audit)

**Expected result:**
Record should be displayed to be assigned to the user who was assigned previously (before the registrar unassigned) in both 'workqueue' and 'record audit'; and when he tries to perform any action on the record, he is shown a toast saying he has been unassigned from that record.

**Screenshot/Recording:**

https://github.com/user-attachments/assets/3c2e664f-276a-4ed1-8afd-97a6cbbc8733

**Tested on:**
https://register.farajaland-qa.opencrvs.org/

**Version:**
v1.7.0

**Comment by tiri39** [comment]
Fixed.
[Record is displayed to be assigned to the registrar]

https://github.com/user-attachments/assets/efd8d4d9-7d6f-429d-ae55-36fc01317c7a

**Comment by tiri39** [comment]
No Fixed.

1. After the second user (ex - registrar) unassigns the first user (ex - RA) and assigns himself to a record; logged in from the first user, that record is shown as assigned to the second user but (Print/ Review/ Update) is enabled in workqueue; although button is disabled in the action menu in record audit page. Whenever the first user tries to perform any action by clicking that enabled button, a toast pops up saying he is unassigned from the record.

2. After the second user (ex - registrar) unassigns the first user (ex - RA) and assigns himself to a record in 'Ready to issue' workqueue; logged in from the first user, that record is shown as assigned to the second user but 'Issue' button is enabled, and actually issues the record though it is assigned to the second user (ex - registrar). 

https://github.com/user-attachments/assets/52545e7f-257b-47aa-ba3d-dd65703356aa

**Comment by tiri39** [comment]
Fixed.

After the second user (ex - registrar) unassigns the first user (ex - RA) and assigns himself to a record; logged in from the first user, that record is shown as assigned to the second user and button in workqueue is disabled.

https://github.com/user-attachments/assets/da4f1903-0347-4fa5-babf-3b4209210bb5

**Comment by Zangetsu101** [comment]
>After the second user (ex - registrar) unassigns the first user (ex - RA) and assigns himself to a record in 'Ready to issue' workqueue; logged in from the first user, that record is shown as assigned to the second user but 'Issue' button is enabled, and actually issues the record though it is assigned to the second user (ex - registrar).

This one I did not fix as it's not really a regression in 1.7 rather it's been here for a while. And the amount of changes required to fix this is not worth it IMO as it's gonna be revamped in events v2 anyway

**Comment by tiri39** [comment]
Not Fixed.

1. Registrar1 unassigns registrar2 from a record. Registrar2 logs in and finds that record still being assigned to himself. When trying to unassign himself from that record, it gets stuck in loading state. 

https://github.com/user-attachments/assets/54424757-5da1-4114-bcd6-865031f5b4f0

**Comment by Zangetsu101** [comment]
>Registrar2 unassigns registrar1 from a record and assigns himself. Registrar1 logs in and finds that record still being assigned to himself. When registrar1 clicks unassign, he gets unassigned from that record and the record is shown as not assigned to anyone. [registrar2 also gets unassigned at this point]
Registrar2 logs in and finds that record being assigned to himself. when trying to perform any action on that record, an error message pops up saying ''You were unassigned from [Tracking ID]".

I think we have veered far enough from the original issue with this. There are quite a bit of grey areas with the assign/unassign feature as it is. I suggest we leave this for now and have a thought about how we should notify another user if they've been unassigned from a record and do so aggressively instead of waiting for an action to be performed by the user. @jpye-finch @rikukissa

**Comment by jpye-finch** [comment]
@eduffus @Zangetsu101 @rikukissa 
I agree @Zangetsu101. We should explore a more aggressive way to inform a user if they have been unassigned. instead of allowing them to continue and only find out went the try to submit an action on the record. 

happy for this to be closed and backlog item raised to consider the above

**Comment by tiri39** [comment]
1. Fixed.
 
https://github.com/user-attachments/assets/2fec810a-beaf-41bd-9c46-e5a69e7e8370

**Comment by marcio-opencrvs** [comment]
Closing this ticket as the entire assign/unassign functionality require further thinking and refactoring @jpye-finch @rikukissa @Zangetsu101
