### ISSUE TITLE
Supporting documents fail to load after cache is cleared.

### ISSUE THREAD

**Issue by tiri39** [opencrvs/opencrvs-core#9254]
**Bug description:**
Supporting documents fail to load after cache is cleared.

**Steps to reproduce:**

1. Login as FA/ RA/ registrar.
2. Create any declaration with supporting doc, comment and signature. 
3. Save it as draft.
4. Clear browser cache.
5. Login again and go to that draft.
6. Observe the supporting docs, comment and signature.

**Actual result:**
- Supporting docs fail to load properly.
- Comment gets cleared.
- Signature gets cleared.

**Expected result:**
- Supporting docs should load properly after clearing cache.
-

**Screenshot/Recording:**

https://github.com/user-attachments/assets/fc1ffc90-40a3-41b6-a1b2-94775d2ffa6d

**Tested on:**
https://register.events-v2-test-environment.opencrvs.dev/v2

**Comment by SyedaAfrida** [comment]
This bug is not fixed

![Image](https://github.com/user-attachments/assets/b0019093-66f9-4331-b4f0-1685553ac526)

**Comment by makelicious** [comment]
Issue fixed in E2E environments, too. Sorry for the hassle.

**Comment by makelicious** [comment]
@rikukissa once you are back, could you check if the download functionality fixes this?

**Comment by SyedaAfrida** [comment]
This bug is not fixed yet

https://github.com/user-attachments/assets/c43b59d2-20bc-4df6-87f0-09ee3596d00f

**Comment by SyedaAfrida** [comment]
Closing this ticket for now as seemed fine in other events and other devices. Might need to reopen again

<img width="1271" height="897" alt="Image" src="https://github.com/user-attachments/assets/e3c0de7c-431a-4366-9005-d1d598b33f66" />
